<?php /* @var $escaper \Magento\Framework\Escaper */ ?>
<?php /* @var $block \Perspective\NovaposhtaShipping\Block\Adminhtml\Order\Shipping\AbstractShipment */ ?>
<?php
switch ($block->getRenderBlock()) {
    case 'w2c':
        $childBlock = $block->getChildBlock('type_address_delivery_person')->setType('w2c');
        echo $childBlock->toHtml();
        break;
    case 'c2c':
        $childBlock = $block->getChildBlock('type_address_delivery_person')->setType('c2c');
        echo $childBlock->toHtml();
        break;
    case 'w2w':
        $childBlock = $block->getChildBlock('type_warehouse_delivery_person')->setType('w2w');
        echo $childBlock->toHtml();
        break;
    case 'c2w':
        $childBlock = $block->getChildBlock('type_warehouse_delivery_person')->setType('c2w');
        echo $childBlock->toHtml();
        break;
}
?>
<!--<script type="text/x-magento-init">-->
<!--    {-->
<!--    "*":{-->
<!--         "Magento_Ui/js/core/app":{-->
<!--            "components":{-->
<!--                "contactPersonSenderInputAutocompleteShipping":{-->
<!--                      "component": "Perspective_NovaposhtaShipping/js/order/shipping/contactPersonSender",-->
<!--                      "backendUrl":"--><?php //= $block->getRestUrl('rest/V1/novaposhtashipping/sender-contact-person') ?><!--"-->
<!--                },-->
<!--                "contactPersonSenderAddressInputAutocompleteShipping":{-->
<!--                      "component": "Perspective_NovaposhtaShipping/js/order/shipping/contactPersonSenderAddress",-->
<!--                      "backendUrl":"--><?php //= $block->getRestUrl('rest/V1/novaposhtashipping/sender-contact-person-address') ?><!--"-->
<!--                }-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--}-->
<!---->
<!--</script>-->
