<?php

namespace Perspective\NovaposhtaShipping\Model;

use Magento\Framework\Model\AbstractExtensibleModel;
use Perspective\NovaposhtaShipping\Api\Data\ShippingCheckoutOnestepPriceCacheInterface;


class ShippingCheckoutOnestepPriceCache extends AbstractExtensibleModel implements ShippingCheckoutOnestepPriceCacheInterface
{
    protected function _construct()
    {
        $this->_init(\Perspective\NovaposhtaShipping\Model\ResourceModel\ShippingCheckoutOnestepPriceCache::class);
    }

    /**
     * @return mixed
     */
    public function getCartId()
    {
        return $this->getData(self::CART_ID);
    }

    /**
     * @param $data
     * @return \Magento\Framework\Model\AbstractModel|\Perspective\NovaposhtaShipping\Model\ShippingWarehouse
     */
    public function setCartId($data)
    {
        return $this->setData(self::CART_ID, $data);
    }


    public function getCachePrice()
    {
        return $this->getData(self::PRICE);
    }

    public function getShippingMethod()
    {
        return $this->getData(self::METHOD);
    }

    public function setCachePrice($data)
    {
        return $this->setData(self::PRICE, $data);
    }

    public function setShippingMethod($data)
    {
        return $this->setData(self::METHOD, $data);
    }
    public function getId()
    {
        return parent::getId(); // TODO: Change the autogenerated stub
    }
    public function setId($value)
    {
        return parent::setId($value); // TODO: Change the autogenerated stub
    }
}
