<?php /* @var $escaper \Magento\Framework\Escaper */ ?>
<?php /* @var $block \Perspective\NovaposhtaShipping\Block\Adminhtml\Order\Shipping\AddressShipment */ ?>
<?php $_order = $block->getOrder() ?>
<?php if (!$block->getIsActive()) {
    return;
} ?>
<?php $block->recalculatePrice() ?>
<section data-bind="scope: 'AddressShippingForm'" class="admin__page-section order-npShippingForm">

    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Create Address to Address Novaposhta delivery') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-AddressShippingForm">
            <form id="npc2c_shipping_form" name="npc2c_shipping_form" method="post">
                <div class="admin__page-section-title">
                    <span class="title"><?php echo __('Preselected by the customer values:') ?></span>
                </div>
                <div style="display: flow-root;" class="row-gray">
                    <label for="np_c2c_city"><?= __('City that has been chosen by the customer') ?></label>
                    <div class="input-to-right">
                        <!--                        cityInputAutocompleteShipping-->
                        <?= $block->getCityAutocompleteHtml() ?>

                    </div>
                </div>
                <br/>
                <div style="display: flow-root;">
                    <label for="np_c2c_street"><?= __('Street that has been chosen by the customer') ?></label>
                    <div class="input-to-right">
                        <!--                        streetInputAutocompleteShipping-->
                        <?= $block->getStreetAutocompleteHtml() ?>

                    </div>
                </div>
                <br/>
                <div style="display: flow-root;" class="row-gray">
                    <label
                        for="np_c2c_street_num"><?= __('Building number that has been chosen by the customer') ?></label>
                    <div class="input-to-right">
                        <input type="text" name="np_c2c_street_num" id="np_c2c_street_num"
                               value="<?php echo $block->getBuildNumData(); ?>"/>
                    </div>
                </div>
                <br/>
                <div style="display: flow-root;">
                    <label for="np_c2c_flat"><?= __('Flat number that has been chosen by the customer') ?></label>
                    <div class="input-to-right">
                        <input type="text" name="np_c2c_flat" id="np_c2c_flat"
                               value="<?php echo $block->getFlat(); ?>"/>
                    </div>
                </div>
                <br/>
                <div class="admin__page-section-title">
                    <span class="title"><?php echo __('Data prediction from NovaPost:') ?></span>
                </div>
                <div class="row-gray" style="display: flow-root;">
                    <label for="np_c2c_prev_calculated_price"><?= __('Recalculated price of delivery:') ?></label>
                    <div class="input-to-right">
                        <label type="text" disabled name="np_c2c_prev_calculated_price"
                               id="np_c2c_prev_calculated_price">
                            <?php
                            $table = [];
                            foreach ($block->getDeiveryPrice() as $ind => $val) {
                                if (isset($val['data'][0]['CostRedelivery'])) {
                                    $cost = $val['data'][0]['Cost'] + $val['data'][0]['CostRedelivery'] . ' (' . $val['data'][0]['Cost'] . '+' . +$val['data'][0]['CostRedelivery'] . ')';
                                    $table [] = '<tr>' . '<td>' . $cost . '</td>' . '</tr>';
                                } else {
                                    if (isset($val['data'][0]['Cost'])) {
                                        $table [] = '<tr>' . '<td>' . $val['data'][0]['Cost'] . '</td>' . '</tr>';
                                    } else {
                                        $table [] = '<tr>' . '<td>' . '0' . '</td>' . '</tr>';
                                    }
                                }
                            }
                            $tableStr = join('', $table);
                            echo '<table><tr><th>' . __('Delivery price') . '</th></tr>' . $tableStr . '</table>';
                            ?>
                        </label>
                    </div>
                </div>
                <br/>
                <div  style="display: flow-root;">
                    <label for="np_c2c_prev_calculated_day"><?= __('Recalculated day of delivery:') ?></label>
                    <div class="input-to-right">
                        <label type="text" disabled name="np_c2c_prev_calculated_day" id="np_c2c_prev_calculated_day">
                            <?php
                            $table = [];
                            foreach ($block->getDeliveryDate() as $ind => $val) {
                                if (isset($val['data'][0]['DeliveryDate']['date'])) {
                                    $table [] = '<tr>' . '<td>' . $val['data'][0]['DeliveryDate']['date'] . '</td>' . '</tr>';
                                } else {
                                    $table [] = '<tr>' . '<td>' . date('d-m-Y') . '</td>' . '</tr>';
                                }
                            }
                            $tableStr = join('', $table);
                            echo '<table><tr><th>' . __('Delivery date') . '</th></tr>' . $tableStr . '</table>';
                            ?>
                        </label>
                    </div>
                </div>
                <br/>
                <input type="hidden" name="order_id" id="order_id" value="<?php echo $_order->getId(); ?>"/>
                <input type="hidden" name="form_key" value="<?php echo $block->getFormKey(); ?>"/>
                <div id="loader"></div>
                <div class="admin__page-section-title">
                    <span class="title"><?php echo __('Sender params:') ?></span>
                </div>

                <div style="display: flow-root;">
                    <label for="np_sender_city"><?= __('Current Sender') ?></label>
                    <div class="input-to-right">
                        <?= $block->getSenderHtml() ?>
                        <?= $block->getSenderHiddenHtml() ?>

                    </div>
                </div>
                <br/>
                <div class="row-gray" style="display: flow-root;">
                    <label for="np_sender_contact_person"><?= __('Choose contact person') ?></label>
                    <div class="input-to-right">
                        <?= $block->getContactPersonHtml() ?>
                        <?= $block->getContactPersonHiddenHtml() ?>
                    </div>
                </div>
                <br/>
                <?php if ($block->isOrganisation()): ?>
                    <div style="display: flow-root;">
                        <label for="np_sender_contact_person"><?= __('Choose contact person address') ?></label>
                        <div class="input-to-right">
                            <?= $block->getContactPersonAddressHtml() ?>
                            <?= $block->getContactPersonAddressHiddenHtml() ?>
                        </div>
                    </div>
                    <br/>
                <?php endif; ?>
                <div style="display: flow-root;">
                    <button type="button" id="create_ttn_c2c" class="scalable save">
                        <span><?php echo __('Send to Novaposhta server the parcel parameters') ?></span>
                    </button>
                </div>
                <div style="display: flow-root;" id="error-list-desc" name="error-list-desc-c2c"></div>
                <div style="display: flow-root;" id="error-list-codes" name="error-list-codes-c2c"></div>
            </form>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
    <?php $childrenBlock = $block->getChildBlock('perspective_autocomplete_address_city_input_js_organisation');
    $childrenBlock->setData('city_value', $block->getCityData());
    $childrenBlock->setData('city_label', $block->getCityLabel());
    $childrenBlock->setData('street_value', $block->getStreetData());
    $childrenBlock->setData('street_label', $block->getStreetLabel());
    ?>
    <?= $childrenBlock->toHtml(); ?>
