<?php /* @var $escaper \Magento\Framework\Escaper */ ?>
<?php /** @var \Perspective\NovaposhtaShipping\Block\Adminhtml\Order\Create\AutocompleteScripts $block */ ?>
<script>
    require([
        'jquery',
        'ko',
        "prototype"
    ], function () {

        <?php /**
     * Максимально мягко вклиниваемся в форму адреса
     */?>

    });
</script>
<?php
echo $block->getChildHtml('perspective_autocomplete_city_x_magento_js');
echo $block->getChildHtml('perspective_autocomplete_street_x_magento_js');
echo $block->getChildHtml('perspective_autocomplete_warehose_x_magento_js');
