<?php /* @var $escaper \Magento\Framework\Escaper */ ?>
<?php /** @var \Perspective\NovaposhtaShipping\Block\Adminhtml\Order\Create\AutocompleteScripts $block */ ?>
<script type="text/x-magento-init">
{
"*":{
     "Magento_Ui/js/core/app":{
        "components":{
            "streetInputAutocompleteShipping":{
                "component": "Perspective_NovaposhtaShipping/js/order/create/street",
                "cityBackendUrl":"<?= $block->getRestUrl('rest/V1/novaposhtashipping/streets-formatted-for-select') ?>",
                "inputName":"order[shipping_address][novaposhta_street]",
                "preselectedValue":"<?= $escaper->escapeJs($block->getStreet()) ?>",
                "preselectedLabel":"<?= $escaper->escapeJs($block->getStreetLabel()) ?>"
                },
            "streetInputAutocompleteBilling":{
                "component": "Perspective_NovaposhtaShipping/js/order/create/street",
                "cityBackendUrl":"<?= $block->getRestUrl('rest/V1/novaposhtashipping/streets-formatted-for-select') ?>",
                "inputName":"order[billing_address][novaposhta_street]",
                "preselectedValue":"<?= $escaper->escapeJs($block->getStreet()) ?>",
                "preselectedLabel":"<?= $escaper->escapeJs($block->getStreetLabel()) ?>"
                },
            "streetInputAutocompleteOrphan":{
                "component": "Perspective_NovaposhtaShipping/js/order/create/street",
                "cityBackendUrl":"<?= $block->getRestUrl('rest/V1/novaposhtashipping/streets-formatted-for-select') ?>",
                "inputName":"novaposhta_street",
                "preselectedValue":"<?= $escaper->escapeJs($block->getStreet()) ?>",
                "preselectedLabel":"<?= $escaper->escapeJs($block->getStreetLabel()) ?>"
                }
            }
        }
    }
}
</script>
