<?php /* @var $escaper \Magento\Framework\Escaper */ ?>
<?php /** @var \Perspective\NovaposhtaShipping\Block\Adminhtml\Order\Create\AutocompleteScripts $block */ ?>
<script type="text/x-magento-init">
{
"*":{
     "Magento_Ui/js/core/app":{
        "components":{
            "streetInputAutocompleteShipping":{
                "component": "Perspective_NovaposhtaShipping/js/order/shipping/street",
                "cityBackendUrl":"<?= $block->getRestUrl('rest/V1/novaposhtashipping/streets-formatted') ?>",
                "inputName":"np_c2c_streetValue",
                "streetLabel":"<?= $block->getStreetLabel() ?>",
                "streetValue":"<?= $block->getStreetValue() ?>"
                }
            }
        }
    }
}
</script>
