<?php /**@var $block \Perspective\NovaposhtaShipping\Block\Adminhtml\Order\NovaposhtaShippingVisualisation */ ?>
<?php /* @var $escaper \Magento\Framework\Escaper */ ?>
<?php if ($block->getEnabled()): ?>
    <section class="admin__page-section order-addresses">
        <div class="admin__page-section-title">
            <span
                class="title"><?= $escaper->escapeHtml(__('Novaposhta Shipping Visualisation(Experimental)')) ?></span>
        </div>
        <?php foreach ($this->getShipping()->getData() as $key => $value): ?>

            <?php if ($block->allowedToShow($key, $value)): ?>
                <div class="admin__page-section-content">
                    <div class="admin__page-section-item order-<?= $key ?>">
                        <div class="admin__page-section-item-title">
                            <span class="title"><?= $escaper->escapeHtml(__($block->decorateLabel($key))) ?></span>
                            <div class="admin__page-section-item-content">
                                <a href="<?= $escaper->escapeUrl($block->decorateValue($key, $value)) ?>"><?= __('Visualise Box #%1', $block->getBoxNumber($key)) ?></a>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </section>
<?php endif ?>
